version: '3'

services:

  web:
    image: nodejs-sample
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:3000
    environment:
      - NODE_ENV=development    
    depends_on:
      - redis

  redis:
    image: redis